version: '3.8'

services:
  courtbookingdb:
    image: postgres:latest
    container_name: courtbookingdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2405
      - POSTGRES_DB=CourtBookingDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_courtbooking:/var/lib/postgresql/data

  courtbooking.api:
    image: courtbooking-api
    build:
      context: .
      dockerfile: src/Services/CourtBooking/CourtBooking.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=courtbookingdb;Port=5432;Database=CourtBookingDB;Username=postgres;Password=2405
    ports:
      - "6003:8080"
      - "6063:8081"
    depends_on:
      - courtbookingdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  postgres_courtbooking:
