name: Build and Dockerize All Services

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: boderuxa

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - src/Services/Coach/Coach.API
          - src/Services/Chat/Chat.API
          - src/Services/Notification/Notification.API
          - src/Services/Payment/Payment
          - src/Services/Review/Review.API
          - src/Gateway/YarpApiGateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          SERVICE_NAME=$(basename ${{ matrix.service }})
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${SERVICE_NAME}:latest
          echo "Building $IMAGE_NAME from ${{ matrix.service }}"
          docker build -t $IMAGE_NAME ${{ matrix.service }}

      - name: Push Docker image
        run: |
          SERVICE_NAME=$(basename ${{ matrix.service }})
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${SERVICE_NAME}:latest
          echo "Pushing $IMAGE_NAME"
          docker push $IMAGE_NAME
