name: Build and Dockerize All Services

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: boderuxa

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: src/Services/Coach/Coach.API
            name: scrmrs-coach-service
          - path: src/Services/Chat/Chat.API
            name: scrmrs-chat-service
          - path: src/Services/Notification/Notification.API
            name: scrmrs-notification-service
          - path: src/Services/Payment/Payment
            name: scrmrs-payment-service
          - path: src/Services/Review/Review.API
            name: scrmrs-review-service
          - path: src/Gateway/YarpApiGateway
            name: scrmrs-gateway

    environment: STAG

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ matrix.name }}:latest
          echo "Building $IMAGE_NAME from ${{ matrix.path }}"
          docker build -t $IMAGE_NAME ${{ matrix.path }}

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ matrix.name }}:latest
          echo "Pushing $IMAGE_NAME"
          docker push $IMAGE_NAME
