name: Publish Docker image

on:
  schedule:
    - cron: '38 8 * * *'
  push:
    branches: [ "staging" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "staging" ]

jobs:
  push_to_registry:
    name: Build and Push Docker Compose Image
    runs-on: ubuntu-latest
    environment: STAG

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image using Docker Compose
        run: |
          docker-compose build
          docker-compose push
